phase:
  - concurrency: 10
    interval: 10
    node: 10
  - concurrency: 10
    interval: 10
    # node: 10
scenarios:
  - url: 'https://test.k6.io/'
    method: 'get'
  - url: 'https://test.k6.io/'
    method: 'get'
